name: Semgrep SAST

on:
  push:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST
        run: semgrep scan --config auto .